name: Release

on: 
  release:
    types: [created, published, prereleased]
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install Linux packages
      run: sudo env DEBIAN_FRONTEND=noninteractive apt-get -qq -y install pbzip2

    - name: Checkout Makeself
      uses: actions/checkout@v2

    - name: Build release
      run: |
        make

    - name: Build release with Windows support
      run: |
        ./make-cmd-release.sh

    - name: Upload to release
      uses: ncipollo/release-action@v1
      with:
        artifacts: ./release/*
        allowUpdates: true
        removeArtifacts: true
        token: ${{ secrets.GITHUB_TOKEN }}
